module.exports.pre = [
    '',
    'Learn to ',
    'Go ',
    'Try to ',
    'Let\'s '
]

module.exports.activities = [
    'Hike',
    'Kayak',
    'Scuba Dive',
    'Surf',
    'Camp',
    'Paint',
    'Dance',
    'Cook',
    'Bake',
    'Sing',
    'Swim',
    'Skydive',
    'Free Dive',
    'Ski',
    'Snowboard',
    'Dirt Bike',
    'Mountain Bike',
    'Draw',
    'Trail Run',
    'Do Yoga',
    'Meditate',
    'Sculpt',
    'Salsa Dance',
    'Tango',
    'Tap Dance',
    'Do Pilates',
    'Mix Drinks',
    'Base Jump',
    'Bungee Jump',
    'Fish',
    'Knit',
    'Code',
    'Forage'
]