module.exports.categories = [
    {
        theme: 'Animals',
        activities: [
            'Beekeeping',
            'Birdwatching',
            'Horseback Riding Class',
            'Horseback Riding Tour',
            'Whale Watching',
            'Meet Farm Animals',
            'Meet Marine Life',
            'Rescue Animals',
            'Safari Tour',
            'Wildlife Encounters',
            'Wildlife Photography',
            'Wildlife Spotting',
            'Wildfire Talk',
        ]
    },
    {
        theme: 'Art and Design',
        activities: [
            'Architecture Tour',
            'Art Class',
            'Art Exhibit',
            'Art Museum Tour',
            'Crafts Class',
            'Fashion Class',
            'Graphic Design Class',
            'Interior Design Class',
            'Photography Class',
            'Photoshoot',
            'Street Art Tour',
            'Visual Design Class'
        ]
    },
    {
        theme: 'Culture, Society, and Science',
        activities: [
            'Business and Entrepreneurship Class',
            'Cultural Dancing',
            'Cultural Festival',
            'Culture Talk',
            'Culture Tour',
            'Factory Tour',
            'Language Class',
            'Office Tour',
            'Politics Talk',
            'Science Class',
            'Science Talk',
            'Science Tour',
            'Social Cause Talk',
            'Social Cause Tour',
            'Volunteering'
        ]
    },
    {
        theme: 'Drink',
        activities: [
            'Beer Drinking Tour',
            'Beer Making Class',
            'Beer Tasting',
            'Brewery Tour',
            'Coffee Drinking Tour',
            'Coffee Making Class',
            'Coffee Tasting',
            'Coffee Farm Tour',
            'Sake Drinking Tour',
            'Sake Making Class',
            'Sake Tasting',
            'Spirits Drinking Tour',
            'Mixology Class',
            'Spirits Tasting',
            'Tea Drinking Tour',
            'Tea Making Class',
            'Tea Tasting',
            'Tea Farm Tour',
            'Tea Ceremony',
            'Wine Drinking Tour',
            'Wine Making Class',
            'Wine Tasting',
            'Wine Pairing Class',
            'Winery Tour',
        ]
    },
    {
        theme: 'Food',
        activities: [
            'Baking Class',
            'Candy Making Class',
            'Canning and Preserving Class',
            'Cheese Making Class',
            'Chocolate Making Class',
            'Cooking Class',
            'Fermentation Class',
            'Knife Skills Class',
            'Pastry Class',
            'Farm Tour',
            'Foraging Tour',
            'Market Tour',
            'Street Food Tour',
            'Cheese Tasting',
            'Chocolate Tasting',
            'Olive Oil Tasting',
            'BBQ',
            'Breakfast',
            'Brunch',
            'Dinner',
            'Lunch',
            'Picnic'
        ]
    },
    {
        theme: 'Entertainment',
        activities: [
            'Fireworks Show',
            'Circus',
            'Comedy Class',
            'Comedy Class and Show',
            'Comedy Show',
            'Dance VIP Access',
            'Dance Backstage Access',
            'Dance Backstage Tour',
            'Dance Class',
            'Dance Class and Show',
            'Dance Party',
            'Dance Performance',
            'Dance Rehearsal Access',
            'Augmented Reality Gaming',
            'Virtual Reality Gaming',
            'Board Games',
            'Card Games',
            'Casino Games',
            'Escape Room',
            'Laser Tag',
            'Paintball',
            'Puzzle Games',
            'Role-Playing Game',
            'Scavenger Hunt',
            'Trivia Game',
            'Video Games',
            'Magic Class',
            'Magic Show',
            'Magic Class and Show',
            'TV Behind the Scenes',
            'TV Guest Appearances',
            'TV Location Tour',
            'Media Production Class',
            'Media Talk',
            'TV Screening',
            'Concert VIP Access',
            'Concert Backstage Access',
            'Concert Backstage Tour',
            'Concert Soundcheck',
            'Music Production Class',
            'Musical Instrument Class',
            'Concert',
            'Bar Crawl',
            'Dance Crawl',
            'Music Crawl',
            'Sporting Event VIP Access',
            'Sporting Event Practice Access',
            'Sporting Event Tailgate',
            'Stadium Tour',
            'Sports Viewing',
            'Extraterrestrial Storytelling',
            'Extraterrestrial Tour',
            'Ghost Storytelling',
            'Ghost Tour',
            'Theater VIP Access',
            'Theater Acting Class',
            'Theater Backstage Access',
            'Theater Backstage Tour',
            'Theater Rehearsal Access',
            'Theatrical Performance'
        ]
    },
    {
        theme: 'History and Literature',
        activities: [
            'History Museum Tour',
            'History Talk',
            'History Tour',
            'Literature Reading',
            'Literature Tour',
            'Storytelling',
            'Writing Class'
        ]
    },
    {
        theme: 'Nature and Outdoors',
        activities: [
            'Backpacking',
            'Camping',
            'Hiking',
            'Environmental Causes Talk',
            'Bay Tour',
            'Cave Tour',
            'Cenote Tour',
            'Coastal Tour',
            'Countryside Tour',
            'Desert Tour',
            'Forest Tour',
            'Hot Spring Tour',
            'Jungle Tour',
            'Lake Tour',
            'National Park Tour',
            'Ocean Tour',
            'River Tour',
            'Volcano Tour',
            'Night Sky Photography',
            'Astronomy',
            'Stargazing',
            'Botany',
            'Farming',
            'Gardening',
            'Herbalism'
        ]
    },
    {
        theme: 'Sightseeing, Shopping, and Transportation',
        activities: [
            'Boat Tour',
            'Cycling Tour',
            'Helicopter Tour',
            'Museum Tour',
            'Plane Tour',
            'Shopping Tour',
            'Car Ride',
            'Flight Lesson',
            'Hot Air Balloon Tour',
            'Photography Tour',
            'Scooter Tour',
            'Sightseeing Tour',
            'Walking Tour'
        ]
    },
    {
        theme: 'Sports',
        activities: [
            'Team Sports',
            'Adrenaline Sports',
            'Boxing',
            'Martial Arts',
            'Workout Class',
            'Crossfit',
            'Dance Fitness',
            'Running',
            'Strength Training',
            'Canyoning',
            'Climbing',
            'Mountain Biking',
            'Rappelling',
            'Trekking',
            'Backpacking',
            'Camping',
            'Fishing',
            'Hunting',
            'Ice Skating',
            'Skiing',
            'Sledding',
            'Snowboarding',
            'Snowmobiling',
            'Snowshoeing',
            'Boating',
            'Canoeing',
            'Diving',
            'Kayaking',
            'Paddleboarding',
            'Sailing',
            'Snorkeling',
            'Surfing',
            'Swimming',
            'Whitewater Rafting'
        ]
    },
    {
        theme: 'Wellness',
        activities: [
            'Fragrance Consultation',
            'Fragrance Workshop',
            'Hair Care Class',
            'Hair Care Consultation',
            'Hair Care Treatment',
            'Hair Care Workshop',
            'Makeup Class',
            'Makeup Consultation',
            'Makeup Workshop',
            'Skincare Class',
            'Skincare Consultation',
            'Skincare Treatment',
            'Skincare Workshop',
            'Bodywork Treatment',
            'Bodywork Workshop',
            'Astrology Class',
            'Astrology Reading',
            'Astrology Workshop',
            'Dream Interpretation Consultation',
            'Dream Interpretation Workshop',
            'Psychic Reading',
            'Psychic Workshop',
            'Tarot Card Reading',
            'Ayurveda Class',
            'Ayurveda Treatment',
            'Ayurveda Workshop',
            'Herbalism Class',
            'Herbalism Treatment',
            'Herbalism Workshop',
            'Nutrition Class',
            'Nutrition Consultation',
            'Nutrition Workshop',
            'Traditional Chinese Medicine Class',
            'Traditional Chinese Medicine Treatment',
            'Traditional Chinese Medicine Workshop',
            'Meditation Class',
            'Meditation Workshop',
            'Mindfulness Ceremony',
            'Stargazing',
            'Breathwork',
            'Circle Gathering',
            'Energy Work',
            'Forest Bathing',
            'Rage Room',
            'Sound Healing',
            'Body Positivity Coaching',
            'Body Positvity Workshop',
            'Personal Growth Coaching',
            'Personal Growth Workshop',
            'Relationships and Sexuality Coaching',
            'Relationships and Sexuality Workshop',
            'Spa Ritual',
            'Spa Tour',
            'Spa Treatment',
            'Spa Workshop',
            'Yoga Class',
            'Yoga Workshop'
        ]
    }
]